Document: workspaces-desktop
Title: Debian workspaces-desktop Manual
Author: <insert document author here>
Abstract: This manual describes what workspaces-desktop is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/workspaces-desktop/workspaces-desktop.sgml.gz

Format: postscript
Files: /usr/share/doc/workspaces-desktop/workspaces-desktop.ps.gz

Format: text
Files: /usr/share/doc/workspaces-desktop/workspaces-desktop.text.gz

Format: HTML
Index: /usr/share/doc/workspaces-desktop/html/index.html
Files: /usr/share/doc/workspaces-desktop/html/*.html
